spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**

        - id: company-service
          uri: lb://company-service
          predicates:
            - Path=/company/**